network:
  version: 2
  renderer: networkd
  ethernets:
    {{ device }}:
      dhcp4: no
      addresses:
        - {{ lan_ip }}/{{ prefix }}
      gateway4: {{ gateway }}
      nameservers:
          search: [{{ domain }}]
          addresses: [{{ name_server }}]
