---
#this playbook configures DHCP on fw-blue13
- name: vyos
  hosts: vyos
  tasks:
    - name: load template
      template:
        src: files/vyos/dhcp.sh.j2
        dest: /tmp/dhcp.sh
        mode: u+rwx
    - name: run the script
      shell: nohup /tmp/dhcp.sh &>/tmp/out.txt &